//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jaahas.OpcUa.JsonEncoding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jaahas.OpcUa.JsonEncoding.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC UA binary type ID {0} does not have a known CLR type..
        /// </summary>
        internal static string Error_CannotFindTypeForTypeId {
            get {
                return ResourceManager.GetString("Error_CannotFindTypeForTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not have a known OPC UA binary type ID..
        /// </summary>
        internal static string Error_CannotFindTypeIdForType {
            get {
                return ResourceManager.GetString("Error_CannotFindTypeIdForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding XML-encoded extension objects to CLR types is not supported..
        /// </summary>
        internal static string Error_DecodingXmlToClrTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Error_DecodingXmlToClrTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node ID type {0} is not valid..
        /// </summary>
        internal static string Error_InvalidNodeIdType {
            get {
                return ResourceManager.GetString("Error_InvalidNodeIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected JSON property &apos;{0}&apos; was not found..
        /// </summary>
        internal static string Error_JsonPropertyNotFound {
            get {
                return ResourceManager.GetString("Error_JsonPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum array length is {0}..
        /// </summary>
        internal static string Error_MaximumArrayLengthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumArrayLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum byte string length is {0} bytes..
        /// </summary>
        internal static string Error_MaximumByteStringLengthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumByteStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum UTF-8 string length is {0} bytes..
        /// </summary>
        internal static string Error_MaximumStringLengthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder encountered an unexpected JSON element type: {0}.
        /// </summary>
        internal static string Error_UnexpectedJsonType {
            get {
                return ResourceManager.GetString("Error_UnexpectedJsonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding {0} is unknown..
        /// </summary>
        internal static string Error_UnknownEncoding {
            get {
                return ResourceManager.GetString("Error_UnknownEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Error_UnsupportedVariantType {
            get {
                return ResourceManager.GetString("Error_UnsupportedVariantType", resourceCulture);
            }
        }
    }
}
